// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: caffe2/proto/prof_dag.proto

#ifndef PROTOBUF_INCLUDED_caffe2_2fproto_2fprof_5fdag_2eproto
#define PROTOBUF_INCLUDED_caffe2_2fproto_2fprof_5fdag_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_caffe2_2fproto_2fprof_5fdag_2eproto CAFFE2_API

namespace protobuf_caffe2_2fproto_2fprof_5fdag_2eproto {
// Internal implementation detail -- do not use these members.
struct CAFFE2_API TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[5];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void CAFFE2_API AddDescriptors();
}  // namespace protobuf_caffe2_2fproto_2fprof_5fdag_2eproto
namespace caffe2 { const ::std::string& GetEmptyStringAlreadyInited(); 
class BlobProfile;
class BlobProfileDefaultTypeInternal;
CAFFE2_API extern BlobProfileDefaultTypeInternal _BlobProfile_default_instance_;
class OpProfile;
class OpProfileDefaultTypeInternal;
CAFFE2_API extern OpProfileDefaultTypeInternal _OpProfile_default_instance_;
class ProfDAGProto;
class ProfDAGProtoDefaultTypeInternal;
CAFFE2_API extern ProfDAGProtoDefaultTypeInternal _ProfDAGProto_default_instance_;
class ProfDAGProtos;
class ProfDAGProtosDefaultTypeInternal;
CAFFE2_API extern ProfDAGProtosDefaultTypeInternal _ProfDAGProtos_default_instance_;
class TwoNumberStatsProto;
class TwoNumberStatsProtoDefaultTypeInternal;
CAFFE2_API extern TwoNumberStatsProtoDefaultTypeInternal _TwoNumberStatsProto_default_instance_;
}  // namespace caffe2
namespace google {
namespace protobuf {
template<> CAFFE2_API ::caffe2::BlobProfile* Arena::CreateMaybeMessage<::caffe2::BlobProfile>(Arena*);
template<> CAFFE2_API ::caffe2::OpProfile* Arena::CreateMaybeMessage<::caffe2::OpProfile>(Arena*);
template<> CAFFE2_API ::caffe2::ProfDAGProto* Arena::CreateMaybeMessage<::caffe2::ProfDAGProto>(Arena*);
template<> CAFFE2_API ::caffe2::ProfDAGProtos* Arena::CreateMaybeMessage<::caffe2::ProfDAGProtos>(Arena*);
template<> CAFFE2_API ::caffe2::TwoNumberStatsProto* Arena::CreateMaybeMessage<::caffe2::TwoNumberStatsProto>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace caffe2 {

// ===================================================================

class CAFFE2_API TwoNumberStatsProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:caffe2.TwoNumberStatsProto) */ {
 public:
  TwoNumberStatsProto();
  virtual ~TwoNumberStatsProto();

  TwoNumberStatsProto(const TwoNumberStatsProto& from);

  inline TwoNumberStatsProto& operator=(const TwoNumberStatsProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TwoNumberStatsProto(TwoNumberStatsProto&& from) noexcept
    : TwoNumberStatsProto() {
    *this = ::std::move(from);
  }

  inline TwoNumberStatsProto& operator=(TwoNumberStatsProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TwoNumberStatsProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TwoNumberStatsProto* internal_default_instance() {
    return reinterpret_cast<const TwoNumberStatsProto*>(
               &_TwoNumberStatsProto_default_instance_);
  }
  static int const kIndexInFileMessages =
    0;

  void Swap(TwoNumberStatsProto* other);
  friend void swap(TwoNumberStatsProto& a, TwoNumberStatsProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TwoNumberStatsProto* New() const final {
    return CreateMaybeMessage<TwoNumberStatsProto>(NULL);
  }

  TwoNumberStatsProto* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TwoNumberStatsProto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TwoNumberStatsProto& from);
  void MergeFrom(const TwoNumberStatsProto& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TwoNumberStatsProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float mean = 1;
  bool has_mean() const;
  void clear_mean();
  static const int kMeanFieldNumber = 1;
  float mean() const;
  void set_mean(float value);

  // optional float stddev = 2;
  bool has_stddev() const;
  void clear_stddev();
  static const int kStddevFieldNumber = 2;
  float stddev() const;
  void set_stddev(float value);

  // optional int64 count = 3;
  bool has_count() const;
  void clear_count();
  static const int kCountFieldNumber = 3;
  ::google::protobuf::int64 count() const;
  void set_count(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:caffe2.TwoNumberStatsProto)
 private:
  void set_has_mean();
  void clear_has_mean();
  void set_has_stddev();
  void clear_has_stddev();
  void set_has_count();
  void clear_has_count();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  float mean_;
  float stddev_;
  ::google::protobuf::int64 count_;
  friend struct ::protobuf_caffe2_2fproto_2fprof_5fdag_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CAFFE2_API BlobProfile : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:caffe2.BlobProfile) */ {
 public:
  BlobProfile();
  virtual ~BlobProfile();

  BlobProfile(const BlobProfile& from);

  inline BlobProfile& operator=(const BlobProfile& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BlobProfile(BlobProfile&& from) noexcept
    : BlobProfile() {
    *this = ::std::move(from);
  }

  inline BlobProfile& operator=(BlobProfile&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BlobProfile& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BlobProfile* internal_default_instance() {
    return reinterpret_cast<const BlobProfile*>(
               &_BlobProfile_default_instance_);
  }
  static int const kIndexInFileMessages =
    1;

  void Swap(BlobProfile* other);
  friend void swap(BlobProfile& a, BlobProfile& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BlobProfile* New() const final {
    return CreateMaybeMessage<BlobProfile>(NULL);
  }

  BlobProfile* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BlobProfile>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BlobProfile& from);
  void MergeFrom(const BlobProfile& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BlobProfile* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional .caffe2.TwoNumberStatsProto bytes_used = 3;
  bool has_bytes_used() const;
  void clear_bytes_used();
  static const int kBytesUsedFieldNumber = 3;
  private:
  const ::caffe2::TwoNumberStatsProto& _internal_bytes_used() const;
  public:
  const ::caffe2::TwoNumberStatsProto& bytes_used() const;
  ::caffe2::TwoNumberStatsProto* release_bytes_used();
  ::caffe2::TwoNumberStatsProto* mutable_bytes_used();
  void set_allocated_bytes_used(::caffe2::TwoNumberStatsProto* bytes_used);

  // @@protoc_insertion_point(class_scope:caffe2.BlobProfile)
 private:
  void set_has_name();
  void clear_has_name();
  void set_has_bytes_used();
  void clear_has_bytes_used();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::caffe2::TwoNumberStatsProto* bytes_used_;
  friend struct ::protobuf_caffe2_2fproto_2fprof_5fdag_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CAFFE2_API ProfDAGProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:caffe2.ProfDAGProto) */ {
 public:
  ProfDAGProto();
  virtual ~ProfDAGProto();

  ProfDAGProto(const ProfDAGProto& from);

  inline ProfDAGProto& operator=(const ProfDAGProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ProfDAGProto(ProfDAGProto&& from) noexcept
    : ProfDAGProto() {
    *this = ::std::move(from);
  }

  inline ProfDAGProto& operator=(ProfDAGProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProfDAGProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ProfDAGProto* internal_default_instance() {
    return reinterpret_cast<const ProfDAGProto*>(
               &_ProfDAGProto_default_instance_);
  }
  static int const kIndexInFileMessages =
    2;

  void Swap(ProfDAGProto* other);
  friend void swap(ProfDAGProto& a, ProfDAGProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ProfDAGProto* New() const final {
    return CreateMaybeMessage<ProfDAGProto>(NULL);
  }

  ProfDAGProto* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ProfDAGProto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ProfDAGProto& from);
  void MergeFrom(const ProfDAGProto& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProfDAGProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .caffe2.BlobProfile output_profile = 5;
  int output_profile_size() const;
  void clear_output_profile();
  static const int kOutputProfileFieldNumber = 5;
  ::caffe2::BlobProfile* mutable_output_profile(int index);
  ::google::protobuf::RepeatedPtrField< ::caffe2::BlobProfile >*
      mutable_output_profile();
  const ::caffe2::BlobProfile& output_profile(int index) const;
  ::caffe2::BlobProfile* add_output_profile();
  const ::google::protobuf::RepeatedPtrField< ::caffe2::BlobProfile >&
      output_profile() const;

  // repeated string extra_info = 7;
  int extra_info_size() const;
  void clear_extra_info();
  static const int kExtraInfoFieldNumber = 7;
  const ::std::string& extra_info(int index) const;
  ::std::string* mutable_extra_info(int index);
  void set_extra_info(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_extra_info(int index, ::std::string&& value);
  #endif
  void set_extra_info(int index, const char* value);
  void set_extra_info(int index, const char* value, size_t size);
  ::std::string* add_extra_info();
  void add_extra_info(const ::std::string& value);
  #if LANG_CXX11
  void add_extra_info(::std::string&& value);
  #endif
  void add_extra_info(const char* value);
  void add_extra_info(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& extra_info() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_extra_info();

  // required string name = 1;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional .caffe2.TwoNumberStatsProto execution_time = 4;
  bool has_execution_time() const;
  void clear_execution_time();
  static const int kExecutionTimeFieldNumber = 4;
  private:
  const ::caffe2::TwoNumberStatsProto& _internal_execution_time() const;
  public:
  const ::caffe2::TwoNumberStatsProto& execution_time() const;
  ::caffe2::TwoNumberStatsProto* release_execution_time();
  ::caffe2::TwoNumberStatsProto* mutable_execution_time();
  void set_allocated_execution_time(::caffe2::TwoNumberStatsProto* execution_time);

  // required float mean = 2;
  bool has_mean() const;
  void clear_mean();
  static const int kMeanFieldNumber = 2;
  float mean() const;
  void set_mean(float value);

  // required float stddev = 3;
  bool has_stddev() const;
  void clear_stddev();
  static const int kStddevFieldNumber = 3;
  float stddev() const;
  void set_stddev(float value);

  // @@protoc_insertion_point(class_scope:caffe2.ProfDAGProto)
 private:
  void set_has_name();
  void clear_has_name();
  void set_has_mean();
  void clear_has_mean();
  void set_has_stddev();
  void clear_has_stddev();
  void set_has_execution_time();
  void clear_has_execution_time();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::caffe2::BlobProfile > output_profile_;
  ::google::protobuf::RepeatedPtrField< ::std::string> extra_info_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::caffe2::TwoNumberStatsProto* execution_time_;
  float mean_;
  float stddev_;
  friend struct ::protobuf_caffe2_2fproto_2fprof_5fdag_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CAFFE2_API ProfDAGProtos : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:caffe2.ProfDAGProtos) */ {
 public:
  ProfDAGProtos();
  virtual ~ProfDAGProtos();

  ProfDAGProtos(const ProfDAGProtos& from);

  inline ProfDAGProtos& operator=(const ProfDAGProtos& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ProfDAGProtos(ProfDAGProtos&& from) noexcept
    : ProfDAGProtos() {
    *this = ::std::move(from);
  }

  inline ProfDAGProtos& operator=(ProfDAGProtos&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProfDAGProtos& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ProfDAGProtos* internal_default_instance() {
    return reinterpret_cast<const ProfDAGProtos*>(
               &_ProfDAGProtos_default_instance_);
  }
  static int const kIndexInFileMessages =
    3;

  void Swap(ProfDAGProtos* other);
  friend void swap(ProfDAGProtos& a, ProfDAGProtos& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ProfDAGProtos* New() const final {
    return CreateMaybeMessage<ProfDAGProtos>(NULL);
  }

  ProfDAGProtos* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ProfDAGProtos>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ProfDAGProtos& from);
  void MergeFrom(const ProfDAGProtos& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProfDAGProtos* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .caffe2.ProfDAGProto stats = 1;
  int stats_size() const;
  void clear_stats();
  static const int kStatsFieldNumber = 1;
  ::caffe2::ProfDAGProto* mutable_stats(int index);
  ::google::protobuf::RepeatedPtrField< ::caffe2::ProfDAGProto >*
      mutable_stats();
  const ::caffe2::ProfDAGProto& stats(int index) const;
  ::caffe2::ProfDAGProto* add_stats();
  const ::google::protobuf::RepeatedPtrField< ::caffe2::ProfDAGProto >&
      stats() const;

  // repeated .caffe2.OpProfile ops_stats = 3;
  int ops_stats_size() const;
  void clear_ops_stats();
  static const int kOpsStatsFieldNumber = 3;
  ::caffe2::OpProfile* mutable_ops_stats(int index);
  ::google::protobuf::RepeatedPtrField< ::caffe2::OpProfile >*
      mutable_ops_stats();
  const ::caffe2::OpProfile& ops_stats(int index) const;
  ::caffe2::OpProfile* add_ops_stats();
  const ::google::protobuf::RepeatedPtrField< ::caffe2::OpProfile >&
      ops_stats() const;

  // optional string net_name = 2;
  bool has_net_name() const;
  void clear_net_name();
  static const int kNetNameFieldNumber = 2;
  const ::std::string& net_name() const;
  void set_net_name(const ::std::string& value);
  #if LANG_CXX11
  void set_net_name(::std::string&& value);
  #endif
  void set_net_name(const char* value);
  void set_net_name(const char* value, size_t size);
  ::std::string* mutable_net_name();
  ::std::string* release_net_name();
  void set_allocated_net_name(::std::string* net_name);

  // @@protoc_insertion_point(class_scope:caffe2.ProfDAGProtos)
 private:
  void set_has_net_name();
  void clear_has_net_name();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::caffe2::ProfDAGProto > stats_;
  ::google::protobuf::RepeatedPtrField< ::caffe2::OpProfile > ops_stats_;
  ::google::protobuf::internal::ArenaStringPtr net_name_;
  friend struct ::protobuf_caffe2_2fproto_2fprof_5fdag_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CAFFE2_API OpProfile : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:caffe2.OpProfile) */ {
 public:
  OpProfile();
  virtual ~OpProfile();

  OpProfile(const OpProfile& from);

  inline OpProfile& operator=(const OpProfile& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  OpProfile(OpProfile&& from) noexcept
    : OpProfile() {
    *this = ::std::move(from);
  }

  inline OpProfile& operator=(OpProfile&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OpProfile& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OpProfile* internal_default_instance() {
    return reinterpret_cast<const OpProfile*>(
               &_OpProfile_default_instance_);
  }
  static int const kIndexInFileMessages =
    4;

  void Swap(OpProfile* other);
  friend void swap(OpProfile& a, OpProfile& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline OpProfile* New() const final {
    return CreateMaybeMessage<OpProfile>(NULL);
  }

  OpProfile* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<OpProfile>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const OpProfile& from);
  void MergeFrom(const OpProfile& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OpProfile* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string idx = 1;
  bool has_idx() const;
  void clear_idx();
  static const int kIdxFieldNumber = 1;
  const ::std::string& idx() const;
  void set_idx(const ::std::string& value);
  #if LANG_CXX11
  void set_idx(::std::string&& value);
  #endif
  void set_idx(const char* value);
  void set_idx(const char* value, size_t size);
  ::std::string* mutable_idx();
  ::std::string* release_idx();
  void set_allocated_idx(::std::string* idx);

  // optional string net_name = 2;
  bool has_net_name() const;
  void clear_net_name();
  static const int kNetNameFieldNumber = 2;
  const ::std::string& net_name() const;
  void set_net_name(const ::std::string& value);
  #if LANG_CXX11
  void set_net_name(::std::string&& value);
  #endif
  void set_net_name(const char* value);
  void set_net_name(const char* value, size_t size);
  ::std::string* mutable_net_name();
  ::std::string* release_net_name();
  void set_allocated_net_name(::std::string* net_name);

  // optional string type = 3;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 3;
  const ::std::string& type() const;
  void set_type(const ::std::string& value);
  #if LANG_CXX11
  void set_type(::std::string&& value);
  #endif
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  ::std::string* mutable_type();
  ::std::string* release_type();
  void set_allocated_type(::std::string* type);

  // optional float exec_time_secs = 4;
  bool has_exec_time_secs() const;
  void clear_exec_time_secs();
  static const int kExecTimeSecsFieldNumber = 4;
  float exec_time_secs() const;
  void set_exec_time_secs(float value);

  // @@protoc_insertion_point(class_scope:caffe2.OpProfile)
 private:
  void set_has_idx();
  void clear_has_idx();
  void set_has_net_name();
  void clear_has_net_name();
  void set_has_type();
  void clear_has_type();
  void set_has_exec_time_secs();
  void clear_has_exec_time_secs();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr idx_;
  ::google::protobuf::internal::ArenaStringPtr net_name_;
  ::google::protobuf::internal::ArenaStringPtr type_;
  float exec_time_secs_;
  friend struct ::protobuf_caffe2_2fproto_2fprof_5fdag_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TwoNumberStatsProto

// optional float mean = 1;
inline bool TwoNumberStatsProto::has_mean() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TwoNumberStatsProto::set_has_mean() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TwoNumberStatsProto::clear_has_mean() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TwoNumberStatsProto::clear_mean() {
  mean_ = 0;
  clear_has_mean();
}
inline float TwoNumberStatsProto::mean() const {
  // @@protoc_insertion_point(field_get:caffe2.TwoNumberStatsProto.mean)
  return mean_;
}
inline void TwoNumberStatsProto::set_mean(float value) {
  set_has_mean();
  mean_ = value;
  // @@protoc_insertion_point(field_set:caffe2.TwoNumberStatsProto.mean)
}

// optional float stddev = 2;
inline bool TwoNumberStatsProto::has_stddev() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TwoNumberStatsProto::set_has_stddev() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TwoNumberStatsProto::clear_has_stddev() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TwoNumberStatsProto::clear_stddev() {
  stddev_ = 0;
  clear_has_stddev();
}
inline float TwoNumberStatsProto::stddev() const {
  // @@protoc_insertion_point(field_get:caffe2.TwoNumberStatsProto.stddev)
  return stddev_;
}
inline void TwoNumberStatsProto::set_stddev(float value) {
  set_has_stddev();
  stddev_ = value;
  // @@protoc_insertion_point(field_set:caffe2.TwoNumberStatsProto.stddev)
}

// optional int64 count = 3;
inline bool TwoNumberStatsProto::has_count() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TwoNumberStatsProto::set_has_count() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TwoNumberStatsProto::clear_has_count() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TwoNumberStatsProto::clear_count() {
  count_ = GOOGLE_LONGLONG(0);
  clear_has_count();
}
inline ::google::protobuf::int64 TwoNumberStatsProto::count() const {
  // @@protoc_insertion_point(field_get:caffe2.TwoNumberStatsProto.count)
  return count_;
}
inline void TwoNumberStatsProto::set_count(::google::protobuf::int64 value) {
  set_has_count();
  count_ = value;
  // @@protoc_insertion_point(field_set:caffe2.TwoNumberStatsProto.count)
}

// -------------------------------------------------------------------

// BlobProfile

// optional string name = 1;
inline bool BlobProfile::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BlobProfile::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BlobProfile::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BlobProfile::clear_name() {
  name_.ClearToEmptyNoArena(&GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& BlobProfile::name() const {
  // @@protoc_insertion_point(field_get:caffe2.BlobProfile.name)
  return name_.GetNoArena();
}
inline void BlobProfile::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:caffe2.BlobProfile.name)
}
#if LANG_CXX11
inline void BlobProfile::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:caffe2.BlobProfile.name)
}
#endif
inline void BlobProfile::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:caffe2.BlobProfile.name)
}
inline void BlobProfile::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:caffe2.BlobProfile.name)
}
inline ::std::string* BlobProfile::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:caffe2.BlobProfile.name)
  return name_.MutableNoArena(&GetEmptyStringAlreadyInited());
}
inline ::std::string* BlobProfile::release_name() {
  // @@protoc_insertion_point(field_release:caffe2.BlobProfile.name)
  if (!has_name()) {
    return NULL;
  }
  clear_has_name();
  return name_.ReleaseNonDefaultNoArena(&GetEmptyStringAlreadyInited());
}
inline void BlobProfile::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:caffe2.BlobProfile.name)
}

// optional .caffe2.TwoNumberStatsProto bytes_used = 3;
inline bool BlobProfile::has_bytes_used() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BlobProfile::set_has_bytes_used() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BlobProfile::clear_has_bytes_used() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BlobProfile::clear_bytes_used() {
  if (bytes_used_ != NULL) bytes_used_->Clear();
  clear_has_bytes_used();
}
inline const ::caffe2::TwoNumberStatsProto& BlobProfile::_internal_bytes_used() const {
  return *bytes_used_;
}
inline const ::caffe2::TwoNumberStatsProto& BlobProfile::bytes_used() const {
  const ::caffe2::TwoNumberStatsProto* p = bytes_used_;
  // @@protoc_insertion_point(field_get:caffe2.BlobProfile.bytes_used)
  return p != NULL ? *p : *reinterpret_cast<const ::caffe2::TwoNumberStatsProto*>(
      &::caffe2::_TwoNumberStatsProto_default_instance_);
}
inline ::caffe2::TwoNumberStatsProto* BlobProfile::release_bytes_used() {
  // @@protoc_insertion_point(field_release:caffe2.BlobProfile.bytes_used)
  clear_has_bytes_used();
  ::caffe2::TwoNumberStatsProto* temp = bytes_used_;
  bytes_used_ = NULL;
  return temp;
}
inline ::caffe2::TwoNumberStatsProto* BlobProfile::mutable_bytes_used() {
  set_has_bytes_used();
  if (bytes_used_ == NULL) {
    auto* p = CreateMaybeMessage<::caffe2::TwoNumberStatsProto>(GetArenaNoVirtual());
    bytes_used_ = p;
  }
  // @@protoc_insertion_point(field_mutable:caffe2.BlobProfile.bytes_used)
  return bytes_used_;
}
inline void BlobProfile::set_allocated_bytes_used(::caffe2::TwoNumberStatsProto* bytes_used) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete bytes_used_;
  }
  if (bytes_used) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      bytes_used = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, bytes_used, submessage_arena);
    }
    set_has_bytes_used();
  } else {
    clear_has_bytes_used();
  }
  bytes_used_ = bytes_used;
  // @@protoc_insertion_point(field_set_allocated:caffe2.BlobProfile.bytes_used)
}

// -------------------------------------------------------------------

// ProfDAGProto

// required string name = 1;
inline bool ProfDAGProto::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProfDAGProto::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProfDAGProto::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProfDAGProto::clear_name() {
  name_.ClearToEmptyNoArena(&GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& ProfDAGProto::name() const {
  // @@protoc_insertion_point(field_get:caffe2.ProfDAGProto.name)
  return name_.GetNoArena();
}
inline void ProfDAGProto::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:caffe2.ProfDAGProto.name)
}
#if LANG_CXX11
inline void ProfDAGProto::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:caffe2.ProfDAGProto.name)
}
#endif
inline void ProfDAGProto::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:caffe2.ProfDAGProto.name)
}
inline void ProfDAGProto::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:caffe2.ProfDAGProto.name)
}
inline ::std::string* ProfDAGProto::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:caffe2.ProfDAGProto.name)
  return name_.MutableNoArena(&GetEmptyStringAlreadyInited());
}
inline ::std::string* ProfDAGProto::release_name() {
  // @@protoc_insertion_point(field_release:caffe2.ProfDAGProto.name)
  if (!has_name()) {
    return NULL;
  }
  clear_has_name();
  return name_.ReleaseNonDefaultNoArena(&GetEmptyStringAlreadyInited());
}
inline void ProfDAGProto::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:caffe2.ProfDAGProto.name)
}

// required float mean = 2;
inline bool ProfDAGProto::has_mean() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ProfDAGProto::set_has_mean() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ProfDAGProto::clear_has_mean() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ProfDAGProto::clear_mean() {
  mean_ = 0;
  clear_has_mean();
}
inline float ProfDAGProto::mean() const {
  // @@protoc_insertion_point(field_get:caffe2.ProfDAGProto.mean)
  return mean_;
}
inline void ProfDAGProto::set_mean(float value) {
  set_has_mean();
  mean_ = value;
  // @@protoc_insertion_point(field_set:caffe2.ProfDAGProto.mean)
}

// required float stddev = 3;
inline bool ProfDAGProto::has_stddev() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ProfDAGProto::set_has_stddev() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ProfDAGProto::clear_has_stddev() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ProfDAGProto::clear_stddev() {
  stddev_ = 0;
  clear_has_stddev();
}
inline float ProfDAGProto::stddev() const {
  // @@protoc_insertion_point(field_get:caffe2.ProfDAGProto.stddev)
  return stddev_;
}
inline void ProfDAGProto::set_stddev(float value) {
  set_has_stddev();
  stddev_ = value;
  // @@protoc_insertion_point(field_set:caffe2.ProfDAGProto.stddev)
}

// optional .caffe2.TwoNumberStatsProto execution_time = 4;
inline bool ProfDAGProto::has_execution_time() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProfDAGProto::set_has_execution_time() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProfDAGProto::clear_has_execution_time() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProfDAGProto::clear_execution_time() {
  if (execution_time_ != NULL) execution_time_->Clear();
  clear_has_execution_time();
}
inline const ::caffe2::TwoNumberStatsProto& ProfDAGProto::_internal_execution_time() const {
  return *execution_time_;
}
inline const ::caffe2::TwoNumberStatsProto& ProfDAGProto::execution_time() const {
  const ::caffe2::TwoNumberStatsProto* p = execution_time_;
  // @@protoc_insertion_point(field_get:caffe2.ProfDAGProto.execution_time)
  return p != NULL ? *p : *reinterpret_cast<const ::caffe2::TwoNumberStatsProto*>(
      &::caffe2::_TwoNumberStatsProto_default_instance_);
}
inline ::caffe2::TwoNumberStatsProto* ProfDAGProto::release_execution_time() {
  // @@protoc_insertion_point(field_release:caffe2.ProfDAGProto.execution_time)
  clear_has_execution_time();
  ::caffe2::TwoNumberStatsProto* temp = execution_time_;
  execution_time_ = NULL;
  return temp;
}
inline ::caffe2::TwoNumberStatsProto* ProfDAGProto::mutable_execution_time() {
  set_has_execution_time();
  if (execution_time_ == NULL) {
    auto* p = CreateMaybeMessage<::caffe2::TwoNumberStatsProto>(GetArenaNoVirtual());
    execution_time_ = p;
  }
  // @@protoc_insertion_point(field_mutable:caffe2.ProfDAGProto.execution_time)
  return execution_time_;
}
inline void ProfDAGProto::set_allocated_execution_time(::caffe2::TwoNumberStatsProto* execution_time) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete execution_time_;
  }
  if (execution_time) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      execution_time = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, execution_time, submessage_arena);
    }
    set_has_execution_time();
  } else {
    clear_has_execution_time();
  }
  execution_time_ = execution_time;
  // @@protoc_insertion_point(field_set_allocated:caffe2.ProfDAGProto.execution_time)
}

// repeated .caffe2.BlobProfile output_profile = 5;
inline int ProfDAGProto::output_profile_size() const {
  return output_profile_.size();
}
inline void ProfDAGProto::clear_output_profile() {
  output_profile_.Clear();
}
inline ::caffe2::BlobProfile* ProfDAGProto::mutable_output_profile(int index) {
  // @@protoc_insertion_point(field_mutable:caffe2.ProfDAGProto.output_profile)
  return output_profile_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::caffe2::BlobProfile >*
ProfDAGProto::mutable_output_profile() {
  // @@protoc_insertion_point(field_mutable_list:caffe2.ProfDAGProto.output_profile)
  return &output_profile_;
}
inline const ::caffe2::BlobProfile& ProfDAGProto::output_profile(int index) const {
  // @@protoc_insertion_point(field_get:caffe2.ProfDAGProto.output_profile)
  return output_profile_.Get(index);
}
inline ::caffe2::BlobProfile* ProfDAGProto::add_output_profile() {
  // @@protoc_insertion_point(field_add:caffe2.ProfDAGProto.output_profile)
  return output_profile_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::caffe2::BlobProfile >&
ProfDAGProto::output_profile() const {
  // @@protoc_insertion_point(field_list:caffe2.ProfDAGProto.output_profile)
  return output_profile_;
}

// repeated string extra_info = 7;
inline int ProfDAGProto::extra_info_size() const {
  return extra_info_.size();
}
inline void ProfDAGProto::clear_extra_info() {
  extra_info_.Clear();
}
inline const ::std::string& ProfDAGProto::extra_info(int index) const {
  // @@protoc_insertion_point(field_get:caffe2.ProfDAGProto.extra_info)
  return extra_info_.Get(index);
}
inline ::std::string* ProfDAGProto::mutable_extra_info(int index) {
  // @@protoc_insertion_point(field_mutable:caffe2.ProfDAGProto.extra_info)
  return extra_info_.Mutable(index);
}
inline void ProfDAGProto::set_extra_info(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:caffe2.ProfDAGProto.extra_info)
  extra_info_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void ProfDAGProto::set_extra_info(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:caffe2.ProfDAGProto.extra_info)
  extra_info_.Mutable(index)->assign(std::move(value));
}
#endif
inline void ProfDAGProto::set_extra_info(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  extra_info_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:caffe2.ProfDAGProto.extra_info)
}
inline void ProfDAGProto::set_extra_info(int index, const char* value, size_t size) {
  extra_info_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:caffe2.ProfDAGProto.extra_info)
}
inline ::std::string* ProfDAGProto::add_extra_info() {
  // @@protoc_insertion_point(field_add_mutable:caffe2.ProfDAGProto.extra_info)
  return extra_info_.Add();
}
inline void ProfDAGProto::add_extra_info(const ::std::string& value) {
  extra_info_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:caffe2.ProfDAGProto.extra_info)
}
#if LANG_CXX11
inline void ProfDAGProto::add_extra_info(::std::string&& value) {
  extra_info_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:caffe2.ProfDAGProto.extra_info)
}
#endif
inline void ProfDAGProto::add_extra_info(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  extra_info_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:caffe2.ProfDAGProto.extra_info)
}
inline void ProfDAGProto::add_extra_info(const char* value, size_t size) {
  extra_info_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:caffe2.ProfDAGProto.extra_info)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
ProfDAGProto::extra_info() const {
  // @@protoc_insertion_point(field_list:caffe2.ProfDAGProto.extra_info)
  return extra_info_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
ProfDAGProto::mutable_extra_info() {
  // @@protoc_insertion_point(field_mutable_list:caffe2.ProfDAGProto.extra_info)
  return &extra_info_;
}

// -------------------------------------------------------------------

// ProfDAGProtos

// repeated .caffe2.ProfDAGProto stats = 1;
inline int ProfDAGProtos::stats_size() const {
  return stats_.size();
}
inline void ProfDAGProtos::clear_stats() {
  stats_.Clear();
}
inline ::caffe2::ProfDAGProto* ProfDAGProtos::mutable_stats(int index) {
  // @@protoc_insertion_point(field_mutable:caffe2.ProfDAGProtos.stats)
  return stats_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::caffe2::ProfDAGProto >*
ProfDAGProtos::mutable_stats() {
  // @@protoc_insertion_point(field_mutable_list:caffe2.ProfDAGProtos.stats)
  return &stats_;
}
inline const ::caffe2::ProfDAGProto& ProfDAGProtos::stats(int index) const {
  // @@protoc_insertion_point(field_get:caffe2.ProfDAGProtos.stats)
  return stats_.Get(index);
}
inline ::caffe2::ProfDAGProto* ProfDAGProtos::add_stats() {
  // @@protoc_insertion_point(field_add:caffe2.ProfDAGProtos.stats)
  return stats_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::caffe2::ProfDAGProto >&
ProfDAGProtos::stats() const {
  // @@protoc_insertion_point(field_list:caffe2.ProfDAGProtos.stats)
  return stats_;
}

// optional string net_name = 2;
inline bool ProfDAGProtos::has_net_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProfDAGProtos::set_has_net_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProfDAGProtos::clear_has_net_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProfDAGProtos::clear_net_name() {
  net_name_.ClearToEmptyNoArena(&GetEmptyStringAlreadyInited());
  clear_has_net_name();
}
inline const ::std::string& ProfDAGProtos::net_name() const {
  // @@protoc_insertion_point(field_get:caffe2.ProfDAGProtos.net_name)
  return net_name_.GetNoArena();
}
inline void ProfDAGProtos::set_net_name(const ::std::string& value) {
  set_has_net_name();
  net_name_.SetNoArena(&GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:caffe2.ProfDAGProtos.net_name)
}
#if LANG_CXX11
inline void ProfDAGProtos::set_net_name(::std::string&& value) {
  set_has_net_name();
  net_name_.SetNoArena(
    &GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:caffe2.ProfDAGProtos.net_name)
}
#endif
inline void ProfDAGProtos::set_net_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_net_name();
  net_name_.SetNoArena(&GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:caffe2.ProfDAGProtos.net_name)
}
inline void ProfDAGProtos::set_net_name(const char* value, size_t size) {
  set_has_net_name();
  net_name_.SetNoArena(&GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:caffe2.ProfDAGProtos.net_name)
}
inline ::std::string* ProfDAGProtos::mutable_net_name() {
  set_has_net_name();
  // @@protoc_insertion_point(field_mutable:caffe2.ProfDAGProtos.net_name)
  return net_name_.MutableNoArena(&GetEmptyStringAlreadyInited());
}
inline ::std::string* ProfDAGProtos::release_net_name() {
  // @@protoc_insertion_point(field_release:caffe2.ProfDAGProtos.net_name)
  if (!has_net_name()) {
    return NULL;
  }
  clear_has_net_name();
  return net_name_.ReleaseNonDefaultNoArena(&GetEmptyStringAlreadyInited());
}
inline void ProfDAGProtos::set_allocated_net_name(::std::string* net_name) {
  if (net_name != NULL) {
    set_has_net_name();
  } else {
    clear_has_net_name();
  }
  net_name_.SetAllocatedNoArena(&GetEmptyStringAlreadyInited(), net_name);
  // @@protoc_insertion_point(field_set_allocated:caffe2.ProfDAGProtos.net_name)
}

// repeated .caffe2.OpProfile ops_stats = 3;
inline int ProfDAGProtos::ops_stats_size() const {
  return ops_stats_.size();
}
inline void ProfDAGProtos::clear_ops_stats() {
  ops_stats_.Clear();
}
inline ::caffe2::OpProfile* ProfDAGProtos::mutable_ops_stats(int index) {
  // @@protoc_insertion_point(field_mutable:caffe2.ProfDAGProtos.ops_stats)
  return ops_stats_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::caffe2::OpProfile >*
ProfDAGProtos::mutable_ops_stats() {
  // @@protoc_insertion_point(field_mutable_list:caffe2.ProfDAGProtos.ops_stats)
  return &ops_stats_;
}
inline const ::caffe2::OpProfile& ProfDAGProtos::ops_stats(int index) const {
  // @@protoc_insertion_point(field_get:caffe2.ProfDAGProtos.ops_stats)
  return ops_stats_.Get(index);
}
inline ::caffe2::OpProfile* ProfDAGProtos::add_ops_stats() {
  // @@protoc_insertion_point(field_add:caffe2.ProfDAGProtos.ops_stats)
  return ops_stats_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::caffe2::OpProfile >&
ProfDAGProtos::ops_stats() const {
  // @@protoc_insertion_point(field_list:caffe2.ProfDAGProtos.ops_stats)
  return ops_stats_;
}

// -------------------------------------------------------------------

// OpProfile

// optional string idx = 1;
inline bool OpProfile::has_idx() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OpProfile::set_has_idx() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OpProfile::clear_has_idx() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OpProfile::clear_idx() {
  idx_.ClearToEmptyNoArena(&GetEmptyStringAlreadyInited());
  clear_has_idx();
}
inline const ::std::string& OpProfile::idx() const {
  // @@protoc_insertion_point(field_get:caffe2.OpProfile.idx)
  return idx_.GetNoArena();
}
inline void OpProfile::set_idx(const ::std::string& value) {
  set_has_idx();
  idx_.SetNoArena(&GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:caffe2.OpProfile.idx)
}
#if LANG_CXX11
inline void OpProfile::set_idx(::std::string&& value) {
  set_has_idx();
  idx_.SetNoArena(
    &GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:caffe2.OpProfile.idx)
}
#endif
inline void OpProfile::set_idx(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_idx();
  idx_.SetNoArena(&GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:caffe2.OpProfile.idx)
}
inline void OpProfile::set_idx(const char* value, size_t size) {
  set_has_idx();
  idx_.SetNoArena(&GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:caffe2.OpProfile.idx)
}
inline ::std::string* OpProfile::mutable_idx() {
  set_has_idx();
  // @@protoc_insertion_point(field_mutable:caffe2.OpProfile.idx)
  return idx_.MutableNoArena(&GetEmptyStringAlreadyInited());
}
inline ::std::string* OpProfile::release_idx() {
  // @@protoc_insertion_point(field_release:caffe2.OpProfile.idx)
  if (!has_idx()) {
    return NULL;
  }
  clear_has_idx();
  return idx_.ReleaseNonDefaultNoArena(&GetEmptyStringAlreadyInited());
}
inline void OpProfile::set_allocated_idx(::std::string* idx) {
  if (idx != NULL) {
    set_has_idx();
  } else {
    clear_has_idx();
  }
  idx_.SetAllocatedNoArena(&GetEmptyStringAlreadyInited(), idx);
  // @@protoc_insertion_point(field_set_allocated:caffe2.OpProfile.idx)
}

// optional string net_name = 2;
inline bool OpProfile::has_net_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OpProfile::set_has_net_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OpProfile::clear_has_net_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OpProfile::clear_net_name() {
  net_name_.ClearToEmptyNoArena(&GetEmptyStringAlreadyInited());
  clear_has_net_name();
}
inline const ::std::string& OpProfile::net_name() const {
  // @@protoc_insertion_point(field_get:caffe2.OpProfile.net_name)
  return net_name_.GetNoArena();
}
inline void OpProfile::set_net_name(const ::std::string& value) {
  set_has_net_name();
  net_name_.SetNoArena(&GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:caffe2.OpProfile.net_name)
}
#if LANG_CXX11
inline void OpProfile::set_net_name(::std::string&& value) {
  set_has_net_name();
  net_name_.SetNoArena(
    &GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:caffe2.OpProfile.net_name)
}
#endif
inline void OpProfile::set_net_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_net_name();
  net_name_.SetNoArena(&GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:caffe2.OpProfile.net_name)
}
inline void OpProfile::set_net_name(const char* value, size_t size) {
  set_has_net_name();
  net_name_.SetNoArena(&GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:caffe2.OpProfile.net_name)
}
inline ::std::string* OpProfile::mutable_net_name() {
  set_has_net_name();
  // @@protoc_insertion_point(field_mutable:caffe2.OpProfile.net_name)
  return net_name_.MutableNoArena(&GetEmptyStringAlreadyInited());
}
inline ::std::string* OpProfile::release_net_name() {
  // @@protoc_insertion_point(field_release:caffe2.OpProfile.net_name)
  if (!has_net_name()) {
    return NULL;
  }
  clear_has_net_name();
  return net_name_.ReleaseNonDefaultNoArena(&GetEmptyStringAlreadyInited());
}
inline void OpProfile::set_allocated_net_name(::std::string* net_name) {
  if (net_name != NULL) {
    set_has_net_name();
  } else {
    clear_has_net_name();
  }
  net_name_.SetAllocatedNoArena(&GetEmptyStringAlreadyInited(), net_name);
  // @@protoc_insertion_point(field_set_allocated:caffe2.OpProfile.net_name)
}

// optional string type = 3;
inline bool OpProfile::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void OpProfile::set_has_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void OpProfile::clear_has_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void OpProfile::clear_type() {
  type_.ClearToEmptyNoArena(&GetEmptyStringAlreadyInited());
  clear_has_type();
}
inline const ::std::string& OpProfile::type() const {
  // @@protoc_insertion_point(field_get:caffe2.OpProfile.type)
  return type_.GetNoArena();
}
inline void OpProfile::set_type(const ::std::string& value) {
  set_has_type();
  type_.SetNoArena(&GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:caffe2.OpProfile.type)
}
#if LANG_CXX11
inline void OpProfile::set_type(::std::string&& value) {
  set_has_type();
  type_.SetNoArena(
    &GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:caffe2.OpProfile.type)
}
#endif
inline void OpProfile::set_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_type();
  type_.SetNoArena(&GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:caffe2.OpProfile.type)
}
inline void OpProfile::set_type(const char* value, size_t size) {
  set_has_type();
  type_.SetNoArena(&GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:caffe2.OpProfile.type)
}
inline ::std::string* OpProfile::mutable_type() {
  set_has_type();
  // @@protoc_insertion_point(field_mutable:caffe2.OpProfile.type)
  return type_.MutableNoArena(&GetEmptyStringAlreadyInited());
}
inline ::std::string* OpProfile::release_type() {
  // @@protoc_insertion_point(field_release:caffe2.OpProfile.type)
  if (!has_type()) {
    return NULL;
  }
  clear_has_type();
  return type_.ReleaseNonDefaultNoArena(&GetEmptyStringAlreadyInited());
}
inline void OpProfile::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    set_has_type();
  } else {
    clear_has_type();
  }
  type_.SetAllocatedNoArena(&GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:caffe2.OpProfile.type)
}

// optional float exec_time_secs = 4;
inline bool OpProfile::has_exec_time_secs() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void OpProfile::set_has_exec_time_secs() {
  _has_bits_[0] |= 0x00000008u;
}
inline void OpProfile::clear_has_exec_time_secs() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void OpProfile::clear_exec_time_secs() {
  exec_time_secs_ = 0;
  clear_has_exec_time_secs();
}
inline float OpProfile::exec_time_secs() const {
  // @@protoc_insertion_point(field_get:caffe2.OpProfile.exec_time_secs)
  return exec_time_secs_;
}
inline void OpProfile::set_exec_time_secs(float value) {
  set_has_exec_time_secs();
  exec_time_secs_ = value;
  // @@protoc_insertion_point(field_set:caffe2.OpProfile.exec_time_secs)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace caffe2

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_caffe2_2fproto_2fprof_5fdag_2eproto
